import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Ride,TRAVEL,duration} from '../engine.mjs';
function run(r,seconds){for(let t=0;t<seconds;t+=.02)r.update(.02)}
function ready(program=3,active=6){const r=new Ride();r.setProgram(program);r.setActive(active);assert(r.command('power'));run(r,4.1);assert(r.command('board'));run(r,10.1);assert(r.command('gates'));assert(r.command('restraints'));run(r,3.1);for(let i=0;i<active;i++)assert(r.check(i));assert(r.command('clear'));run(r,30);assert(r.allowed('dispatch'));return r}
for(const program of [1,2,3])for(const active of [2,4,6])test(`full cycle program ${program}, ${active} lanes`,()=>{const r=ready(program,active);assert(r.command('dispatch'));let previous=0;for(let t=0;t<duration(program)+1;t+=.02){r.update(.02);assert(r.cars.every(c=>c.height>=0&&c.height<=TRAVEL));assert(Math.abs(r.cars[0].height-previous)<.5);previous=r.cars[0].height;if(r.phase==='running'){assert(!r.allowed('restraints'));assert(!r.allowed('gates'));assert(!r.allowed('power'));assert(!r.setProgram(1));assert(!r.setActive(2))}}assert.equal(r.rides,1);assert.equal(r.served,active*8);assert(r.atStation);assert(!r.allowed('dispatch'));assert(r.command('restraints'));assert(r.command('gates'));assert(r.command('unload'));run(r,8.1);assert.equal(r.occupied,0);assert(r.allowed('board'))});
test('individual checks and gates invalidate dispatch',()=>{const r=ready();assert(r.command('gates'));assert(!r.allowed('dispatch'));assert(r.command('gates'));assert(!r.allowed('dispatch'));assert(r.command('clear'));assert(r.allowed('dispatch'));assert(r.command('restraints'));assert(!r.checked);assert(!r.allowed('dispatch'))});
test('emergency brakes continuously; requires recovery and explicit reset',()=>{const r=ready(2);r.command('dispatch');run(r,7);const height=r.cars[0].height;assert(height>1);assert(r.command('stop'));assert.equal(r.cars[0].height,height);assert(!r.allowed('reset'));assert(!r.allowed('gates'));assert(!r.allowed('restraints'));run(r,5);assert.equal(r.phase,'halted');assert(!r.allowed('recover'));assert(r.command('release'));assert(!r.allowed('reset'));assert(r.command('recover'));run(r,60);assert(r.atStation);assert(r.command('reset'));assert.equal(r.rides,0);assert.equal(r.served,0);assert.equal(r.aborted,1);assert(!r.allowed('dispatch'));assert(r.restraints);assert(r.command('restraints'))});
test('stop during loading can be reset without spawning guests',()=>{const r=new Ride();r.command('power');run(r,5);r.command('board');run(r,3);assert(r.command('stop'));run(r,15);assert.equal(r.occupied,0);assert(r.command('release'));assert(r.command('reset'));assert(r.allowed('board'))});
test('no entry, dispatch, release or lane change bypasses interlocks',()=>{const r=new Ride();for(const action of ['dispatch','board','unload','restraints','clear','recover','reset'])assert(!r.command(action));r.command('power');run(r,5);r.command('board');run(r,11);assert(!r.setActive(2));assert(!r.command('dispatch'));assert(!r.check(0));assert(!r.command('power'))});
